spring.application.name=appLogin

server.port=${PORT:8080}
server.address=0.0.0.0

# Proxy Fly.io
server.forward-headers-strategy=framework

spring.jpa.open-in-view=true
spring.main.lazy-initialization=true

cloudinary.cloud_name=dqfudtwbu
cloudinary.api_key=731555525516774
cloudinary.api_secret=GgrO5aWdDuiSkCsOlxPW-MkHnhc